### ISSUE TITLE
Stop reconciliation cycles for CR succesfully reconciled

### ISSUE THREAD

**Issue by jacopoberta** [krateoplatformops/provider-runtime#1]
**Is your feature request related to a problem? Please describe.**
Some providers (eg. Azure Devops Providers) consume API that may have usage limits thresholds. The API limits can be easily exceeded if the provider needs to reconcile a large number of CR.

**Describe the solution you'd like**
A possible solution is to have a new annotation/parameter that will stop reconciliation cycles if the CR has been already reconciled. Providers that try to reconcile CR with this annotation will have to check whether the CR has been already been reconciled with success or not. If the CR has never been reconciled with success, the provider should try to reconcile it, otherwise the CR should be skipped.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jacopoberta** [comment]
a valid alternative to this feature request is to have 2 different reconciliation time interval:

1. first time interval is used to reconcile un-synced CR
2. second time interval is used to reconcile CR already synced.

**Comment by lucasepe** [comment]
This is a barebone library, a tool. It's responsibility of the specific operator to eventually handle an API server call rate limit.
